version: '2'
services:
  db:
    image: postgres
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data/

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "80:3000"
    depends_on:
      - db

volumes:
  postgres-db-volume: