default: &default
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: postgres
  password:
  host: db

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  
