default: &default
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3
  adapter: sqlite3

test:
  <<: *default
  database: db/test.sqlite3
  adapter: sqlite3

production:
  <<: *default
  adapter: postgresql
  database: myapp_development
  encoding: unicode
  username: postgres
  password:
  host: db
  
